@host = http://localhost:3333
@Authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJfaWQiOiI2NTViMzMzOTQyNjg3YjJjNDYwNjc0YWUiLCJpYXQiOjE3MDE0MjA3NTIsImV4cCI6MTcwMjAyNTU1Mn0.DCZsTTWxblrGtIp09ox2zORc_DTnnFyDJEltYp_ol1s

### 添加系统用户
POST {{host}}/users/add
Content-Type: application/json
Authorization: {{Authorization}}

{"username": "test","pwd": "123456"}

### 删除系统用户
POST {{host}}/users/del
Content-Type: application/json
Authorization: {{Authorization}}

{"username": "test"}

### 修改系统用户1
POST {{host}}/users/update
Content-Type: application/json
Authorization: {{Authorization}}

{"username": "test","pwd": "123456"}

### 修改系统用户2
POST {{host}}/users/update
Content-Type: application/json
Authorization: {{Authorization}}

{"username": "test","pwd": "123"}

### 查询所有系统用户
GET {{host}}/users/find
Authorization: {{Authorization}}

### 查询某个系统用户
GET {{host}}/users/find/test
Authorization: {{Authorization}}