@host = http://localhost:3333
@Authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJfaWQiOiI2NWE2Njg1M2Y4YmE3ODA1YzEyMTJjZTgiLCJpYXQiOjE3MDU0MDUyNDYsImV4cCI6MTcwNjAxMDA0Nn0.yX3z-BtUcC49xisSdz-7rzqlLiITX3wZq7ts7augTxk

### 注册
POST {{host}}/users/sign
Content-Type: application/json

{"username": "test","pwd": "123456"}

### 登录1
POST {{host}}/users/login
Content-Type: application/json

{"username": "test","pwd": "123456"}

### 登录2
POST {{host}}/users/login
Content-Type: application/json

{"username": "test","pwd": "123"}

### 验证token
POST {{host}}/users/verify
Content-Type: application/json
Authorization: {{Authorization}}

### 修改密码1
POST {{host}}/users/changePwd
Content-Type: application/json
Authorization: {{Authorization}}

{"username": "test","pwd": "123456"}

### 修改密码2
POST {{host}}/users/changePwd
Content-Type: application/json
Authorization: {{Authorization}}

{"username": "test","pwd": "123"}