<template>
  <el-popover placement="bottom" :width="600" trigger="click">
    <!-- 弹出框 -->
    <div class="icon-list width-100">
      <div v-for="item in iconList" :key="item" class="icon-box flex-center" @click="changeIcon(item)">
        <!-- 图标 -->
        <el-icon class="icon"> <component :is="item" class="pointer" /></el-icon>
      </div>
    </div>
    <template #reference>
      <!-- 输入框 -->
      <el-input v-model.trim="icon" @change="changeIcon"></el-input>
    </template>
  </el-popover>
</template>

<script setup>
import { ref, defineEmits } from 'vue'
let icon = ref('')
const emits = defineEmits(['update:modelValue'])
// 改变图标值图标值
const changeIcon = (item) => {
  icon.value = item
  emits('update:modelValue', item)
}
// element-ui图标列表
const iconList = [
  'AddLocation',
  'Aim',
  'AlarmClock',
  'Apple',
  'ArrowDownBold',
  'ArrowDown',
  'ArrowLeftBold',
  'ArrowLeft',
  'ArrowRightBold',
  'ArrowRight',
  'ArrowUpBold',
  'ArrowUp',
  'Avatar',
  'Back',
  'Baseball',
  'Basketball',
  'BellFilled',
  'Bell',
  'Bicycle',
  'BottomLeft',
  'BottomRight',
  'Bottom',
  'Bowl',
  'Box',
  'Briefcase',
  'BrushFilled',
  'Brush',
  'Burger',
  'Calendar',
  'CameraFilled',
  'Camera',
  'CaretBottom',
  'CaretLeft',
  'CaretRight',
  'CaretTop',
  'Cellphone',
  'ChatDotRound',
  'ChatDotSquare',
  'ChatLineRound',
  'ChatLineSquare',
  'ChatRound',
  'ChatSquare',
  'Check',
  'Checked',
  'Cherry',
  'Chicken',
  'CircleCheckFilled',
  'CircleCheck',
  'CircleCloseFilled',
  'CircleClose',
  'CirclePlusFilled',
  'CirclePlus',
  'Clock',
  'CloseBold',
  'Close',
  'Cloudy',
  'CoffeeCup',
  'Coffee',
  'Coin',
  'ColdDrink',
  'CollectionTag',
  'Collection',
  'Comment',
  'Compass',
  'Connection',
  'Coordinate',
  'CopyDocument',
  'Cpu',
  'CreditCard',
  'Crop',
  'DArrowLeft',
  'DArrowRight',
  'DCaret',
  'DataAnalysis',
  'DataBoard',
  'DataLine',
  'DeleteFilled',
  'DeleteLocation',
  'Delete',
  'Dessert',
  'Discount',
  'DishDot',
  'Dish',
  'DocumentAdd',
  'DocumentChecked',
  'DocumentCopy',
  'DocumentDelete',
  'DocumentRemove',
  'Document',
  'Download',
  'Drizzling',
  'EditPen',
  'Edit',
  'ElemeFilled',
  'Eleme',
  'ElementPlus',
  'Expand',
  'Failed',
  'Female',
  'Files',
  'Film',
  'Filter',
  'Finished',
  'FirstAidKit',
  'Flag',
  'Fold',
  'FolderAdd',
  'FolderChecked',
  'FolderDelete',
  'FolderOpened',
  'FolderRemove',
  'Folder',
  'Food',
  'Football',
  'ForkSpoon',
  'Fries',
  'FullScreen',
  'GobletFull',
  'GobletSquareFull',
  'GobletSquare',
  'Goblet',
  'GoodsFilled',
  'Goods',
  'Grape',
  'Grid',
  'Guide',
  'Headset',
  'HelpFilled',
  'Help',
  'Hide',
  'Histogram',
  'HomeFilled',
  'HotWater',
  'House',
  'IceCreamRound',
  'IceCreamSquare',
  'IceCream',
  'IceDrink',
  'IceTea',
  'InfoFilled',
  'Iphone',
  'Key',
  'KnifeFork',
  'Lightning',
  'Link',
  'List',
  'Loading',
  'LocationFilled',
  'LocationInformation',
  'Location',
  'Lock',
  'Lollipop',
  'MagicStick',
  'Magnet',
  'Male',
  'Management',
  'MapLocation',
  'Medal',
  'Menu',
  'MessageBox',
  'Message',
  'Mic',
  'Microphone',
  'MilkTea',
  'Minus',
  'Money',
  'Monitor',
  'MoonNight',
  'Moon',
  'MoreFilled',
  'More',
  'MostlyCloudy',
  'Mouse',
  'Mug',
  'MuteNotification',
  'Mute',
  'NoSmoking',
  'Notebook',
  'Notification',
  'Odometer',
  'OfficeBuilding',
  'Open',
  'Operation',
  'Opportunity',
  'Orange',
  'Paperclip',
  'PartlyCloudy',
  'Pear',
  'PhoneFilled',
  'Phone',
  'PictureFilled',
  'PictureRounded',
  'Picture',
  'PieChart',
  'Place',
  'Platform',
  'Plus',
  'Pointer',
  'Position',
  'Postcard',
  'Pouring',
  'Present',
  'PriceTag',
  'Printer',
  'Promotion',
  'QuestionFilled',
  'Rank',
  'ReadingLamp',
  'Reading',
  'RefreshLeft',
  'RefreshRight',
  'Refresh',
  'Refrigerator',
  'RemoveFilled',
  'Remove',
  'Right',
  'ScaleToOriginal',
  'School',
  'Scissor',
  'Search',
  'Select',
  'Sell',
  'SemiSelect',
  'Service',
  'SetUp',
  'Setting',
  'Share',
  'Ship',
  'Shop',
  'ShoppingBag',
  'ShoppingCartFull',
  'ShoppingCart',
  'Smoking',
  'Soccer',
  'SoldOut',
  'SortDown',
  'SortUp',
  'Sort',
  'Stamp',
  'StarFilled',
  'Star',
  'Stopwatch',
  'SuccessFilled',
  'Sugar',
  'Suitcase',
  'Sunny',
  'Sunrise',
  'Sunset',
  'SwitchButton',
  'Switch',
  'TakeawayBox',
  'Ticket',
  'Tickets',
  'Timer',
  'ToiletPaper',
  'Tools',
  'TopLeft',
  'TopRight',
  'Top',
  'TrendCharts',
  'Trophy',
  'TurnOff',
  'Umbrella',
  'Unlock',
  'UploadFilled',
  'Upload',
  'UserFilled',
  'User',
  'Van',
  'VideoCameraFilled',
  'VideoCamera',
  'VideoPause',
  'VideoPlay',
  'View',
  'WalletFilled',
  'Wallet',
  'WarningFilled',
  'Warning',
  'Watch',
  'Watermelon',
  'WindPower',
  'ZoomIn',
  'ZoomOut'
]
</script>

<style scoped>
.icon-list {
  height: 300px;
  display: flex;
  flex-wrap: wrap;
  overflow-y: auto;
}
.icon-box {
  width: 35px;
  height: 35px;
  overflow: hidden;
}
.icon {
  font-size: 20px;
}
.pointer:hover {
  cursor: pointer;
}
</style>
